VPATH = src/ test/
NVCC_FLAGS= -arch=sm_75 -std=c++14 -O0
USER_FLAGS= 

LINK= -lcufft -lcurand

RANDOM_GENERATOR_FILES = CUFCM_RANDOM_MAIN.cu CUFCM_RANDOMPACKER.cu CUFCM_DATA.cu CUFCM_CELLLIST.cu
CUFCM_FILES =  CUFCM_MAIN.cu CUFCM_CELLLIST.cu CUFCM_FCM.cu CUFCM_DATA.cu CUFCM_CORRECTION.cu CUFCM_SOLVER.cu
TEST_FILES = CUFCM_TEST.cu CUFCM_CELLLIST.cu CUFCM_FCM.cu CUFCM_DATA.cu CUFCM_CORRECTION.cu CUFCM_SOLVER.cu


CUFCM : $(CUFCM_FILES)
	nvcc $^ $(NVCC_FLAGS) $(LINK) -o bin/$@

CUFCM_DOUBLE : $(CUFCM_FILES)
	nvcc $^ -DUSE_DOUBLE_PRECISION $(NVCC_FLAGS) $(LINK) -o bin/CUFCM

FCM : $(CUFCM_FILES)
	nvcc $^ -DUSE_REGULARFCM $(NVCC_FLAGS) $(LINK) -o bin/$@

FCM_DOUBLE : $(CUFCM_FILES)
	nvcc $^ -DUSE_REGULARFCM -DUSE_DOUBLE_PRECISION $(NVCC_FLAGS) $(LINK) -o bin/FCM

FLOWFIELD : $(CUFCM_FILES)
	nvcc $^ $(NVCC_FLAGS) $(LINK) -o bin/$@

RANDOM_GENERATOR : $(RANDOM_GENERATOR_FILES)
	nvcc $^ $(NVCC_FLAGS) $(LINK) -o bin/RANDOM

TEST : $(TEST_FILES)
	nvcc $^ $(NVCC_FLAGS) $(LINK) -o bin/$@

clean :
	rm -f bin/TEST
	rm -f bin/FCM
	rm -f bin/CUFCM
